# -----------------------------
# Swagger UI
# -----------------------------
# Ruta donde estará Swagger UI
quarkus.swagger-ui.path=/swagger-ui

# -----------------------------
# OpenAPI / generación YAML
# -----------------------------
# Estrategia de nombres de los operationId
mp.openapi.extensions.smallrye.operation-id-strategy=METHOD

# -----------------------------
# Desactivar la generación automática del openapi.yaml
# -----------------------------
quarkus.smallrye-openapi.always-run-generator=false
