# ====================
# DATABASE CONFIGURATION (POSTGRESQL LOCAL)
# ====================

# Tipo de base de datos
quarkus.datasource.db-kind=postgresql

# Configuración JDBC (OBLIGATORIA cuando usas Hibernate)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banco_db
quarkus.datasource.username=postgres
quarkus.datasource.password=Br@_9704

# Pool de conexiones
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.min-size=3
quarkus.datasource.jdbc.initial-size=3

# Desactivar Dev Services (NO se usa cuando hay jdbc.url)
quarkus.datasource.devservices.enabled=false


# ====================
# HIBERNATE CONFIGURATION
# ====================

# Estrategia de generación del esquema
quarkus.hibernate-orm.database.generation=update

# Logs SQL (solo desarrollo)
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Logs detallados
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql".level=TRACE


# ====================
# QUARKUS DEV MODE
# ====================

# Puerto de la aplicación
quarkus.http.port=8080

# Contexto raíz
quarkus.http.root-path=/
